server:
  port: 8080
  servlet:
    context-path: /cinema
  error:
    include-message: always         # Hiển thị thông báo lỗi chi tiết trong response
    include-binding-errors: always  # Hiển thị lỗi validate (VD: @Valid)
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: mimiduy2810@gmail.com
    password: fdjjfrvwgqoywuxf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://dpg-d4cum3c9c44c7392ehig-a.virginia-postgres.render.com:5432/cinemadb_lhyn
    username: cinemadb_lhyn_user
    password: HjvKyrGgZqhF7lsrGIB8J7ABaE0GmVLY
    driver-class-name: org.postgresql.Driver
#  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.messaging: DEBUG

    org.springframework.web.servlet: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    com.fasterxml.jackson: DEBUG
jwt:
  signerKey: "XFM9kjb9Kx5UPtq2q9A1zN6TODrw+4T1KM1T4GpPW3dM+hCFdqMG/OjpieWehRco"
management:
  endpoints:
    web:
      exposure:
        include: mappings, health  # Hiển thị các endpoint và trạng thái